title: "Kartik Goswami"
email: kartikgoswami703@gmail.com
description: >-
  Portfolio of Kartik Goswami - MSc in Data Science & AI at Newcastle University.
baseurl: "" # For GitHub Pages
url: "https://kartik703.github.io"
theme: minima

author:
  name: Kartik Goswami
  email: goswamikartik429@gmail.com

markdown: kramdown
plugins:
  - jekyll-feed

# Disable blog layout (optional)
show_excerpts: false
paginate: false
